### PR TITLE
feat: allow user-specified analytics client

### PR DESCRIPTION
**Pull request by bertrandk**
This gets us away from implicitly relying on the DOM and clears the way
for better Node and RN integration.

### CODE REVIEW

**Comment by alexstrat** [comment]
Any chance too see this merged soon? Can i help on something?

**Comment by atu** [comment]
@alexstrat I guess we have to do it :)

**Comment by bertrandk** [comment]
@alexstrat @atu Try v1.6.0 and let me know if it suits your needs. 😅

**Comment by th3fallen** [comment]
Any chance you could do a changelog in the future or document what changed when you do a new version, i had to do some hunting to find what changed to see if it was a safe update :)

**Comment by bertrandk** [comment]
@th3fallen Yeah, I think #11 is past due actually.

**Comment by atu** [comment]
@bertrandk Sounds amazing. It's working, but should I have 2 different store with the client analytics and the analytics-node?

**Comment by oyeanuj** [comment]
@atu Have the same question as you - where did you end with this?

**Pull request merged**
