### PR TITLE
fix(page): use expected router page event

### PR DESCRIPTION
**Pull request by jhabdas**
@bertrandk I flubbed on the event name. This PR includes the expected event name, as shown in the image here.

screen shot 2016-03-16 at 11 55 37 pm

### CODE REVIEW

**Comment by bertrandk** [comment]
Ah...no worries. Let me cut a new build.

**Comment by jhabdas** [comment]
Thank again. Sorry for the goof in #17. Before submitting this I also tried running the tests I wasn't able to get working the first time around - saw the same result.

**Comment by bertrandk** [comment]
Not an issue. Check out v0.7.2 and let me know.

**Comment by jhabdas** [comment]
Works like a charm!

screen shot 2016-03-17 at 12 14 12 am

**Comment by bertrandk** [comment]
:tada: Awesome. Thanks :smile:

**Pull request merged**
