### PR TITLE
Fix Build Issue

### PR DESCRIPTION
**Pull request by r-bansal**
Closes issues #36 #25 #28

Before closing:
- [ ] Update version number 
- [ ] integrate with CI build (are we building /dist via the CI)

### CODE REVIEW

**Comment by bertrandk** [comment]
:shipit:

**Comment by morenoh149** [comment]
what's blocking this?

**Comment by r-bansal** [comment]
@morenoh149: Will merge shortly :)

**Comment by morenoh149** [comment]
can we get an npm release? :)

**Pull request merged**
